databases:
  - name: postgres
    ipAllowList: []
    databaseName: photo_app_render
    user: photo_app_render

services:
  - type: web
    name: photo_app_render
    env: ruby
    buildCommand: './render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
